### PR TITLE
Basic End to End test on express passes

### PR DESCRIPTION
**Pull request by Try-Try-Again**
End to End test passes on for serving boilerplate html with Express

### CODE REVIEW

**Comment by jbalbin3** [comment]
Haven't checkout how to write tests yet but had a question on line 1:

**Comment by jbalbin3** [comment]
describe('Google', () => {       <---  is this correct.  What's Google there for?

**Comment by Try-Try-Again** [comment]
Good catch! I'm not sure why it's not changed in my commit.

**Comment by Try-Try-Again** [comment]
I used the tutorial's google test to build out my own test. I forgot to change the name after I modified it.

**Comment by jbalbin3** [comment]
lgtm

**Comment by tombohere** [comment]
i need to start thinking about testing as well..  looks good

**Pull request merged**
